### ISSUE TITLE
Add function type: cloudevent

### ISSUE THREAD

**Issue by subfuzion** [GoogleCloudPlatform/functions-framework-dart#1]
https://github.com/GoogleCloudPlatform/functions-framework#cloudevents-functions-signature-type-cloudevent

- [x] Structured event type
- [x] Binary event type
- [x] Pass conformance tests
- [ ] disallow requests with the wrong shape with the correct 4XX response
- [ ] add unit and integration tests for Cloud Events (at the moment, we're validated only with conformance tests)
- [x] kill the process it it tries to startup with a mismatched

**Comment by grant** [comment]
Parse these HTTP requests:

```
POST / HTTP/1.1
Content-Type: application/json; charset=utf-8
Content-Length: 33
ce-specversion: 1.0
ce-type: google.cloud.pubsub.topic.publish
ce-time: 2020-09-05T03:56:24Z
ce-id: 1234-1234-1234
{
 "subscription": "projects/my-project/subscriptions/my-subscription",
 "message": {
   "@type": "type.googleapis.com/google.pubsub.v1.PubsubMessage",
   "attributes": {
     "attr1":"attr1-value"
   },
   "data": "dGVzdCBtZXNzYWdlIDM="
 }
}
```

```
POST / HTTP/1.1
Content-Type: application/json; charset=utf-8
{
  specversion: 1.0
  type: google.cloud.pubsub.topic.publish
  time: 2020-09-05T03:56:24Z
  id: 1234-1234-1234
  data: {
    "subscription": "projects/my-project/subscriptions/my-subscription",
    "message": {
      "@type": "type.googleapis.com/google.pubsub.v1.PubsubMessage",
      "attributes": {
        "attr1":"attr1-value"
      },
      "data": "dGVzdCBtZXNzYWdlIDM="
    }
  }
}
```

**Comment by grant** [comment]
HTTP return value doesn't matter. See FF GitHub repo readme: https://github.com/GoogleCloudPlatform/functions-framework

**Comment by grant** [comment]
Here's example code for how to receive a CloudEvent in the FF:

- Check if the HTTP request`isBinary`: https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/src/cloudevents.ts#L28
  - Get the correct CloudEvent (if binary or structured, see above for difference).
- invoke a users function with a CloudEvent: https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/src/invoker.ts#L145

Do note that the Pub/Sub emulator is not compatible with CloudEvents (and thus the Functions Framework), so don't use it. Use cURL and unit tests to test the functionality.
