### ISSUE TITLE
Expose more in `RequestContext`

### ISSUE THREAD

**Issue by kevmoo** [GoogleCloudPlatform/functions-framework-dart#127]
We can't (er, shouldn't?) expose the entire `Request` because we read the body.

But that leaves some things not accessible to custom and CloudEvent handlers

Including:

- requestedUri
- HTTP method
- protocol version

Follow-up to https://github.com/GoogleCloudPlatform/functions-framework-dart/issues/108

**Comment by subfuzion** [comment]
Perhaps it's best to simply document that accessing the body is an error since the stream has already been read?

**Comment by kevmoo** [comment]
> Perhaps it's best to simply document that accessing the body is an error since the stream has already been read?

Yeah. That makes this all a lot easier. Hrm...

Is there any (good) reason to hide the request otherwise?

**Comment by subfuzion** [comment]
I'm familiar with middleware (like the express json middleware) replacing the request body after parsing the stream so that it can be accessed. Since `body` is dynamic, can our wrapper (or can we create a wrapper to) override?

**Comment by subfuzion** [comment]
But if I understood your question correctly, I don't think we can anticipate all the reasons why someone wants access to the raw request, I don't recommend making it completely inaccessible.
