### ISSUE TITLE
README implies Cloud Functions support Dart

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/functions-framework-dart#130]
The README says the functions can be deployed to Cloud Functions? As far as I know, that's no possible, correct?

**Comment by subfuzion** [comment]
Not yet, no. Still a work in progress, but I can edit for clarity.

**Comment by subfuzion** [comment]
@steren Works great with Cloud Run! (See [docs](https://github.com/GoogleCloudPlatform/functions-framework-dart/blob/main/docs/quickstarts/03-quickstart-cloudrun.md)  :)
