### ISSUE TITLE
Upgrade to a more strict analysis_server ruleset

### ISSUE THREAD

**Issue by craiglabenz** [GoogleCloudPlatform/functions-framework-dart#154]
A lot of the Flutter community uses [this analysis package](https://pub.dev/packages/very_good_analysis) for a starting point for Dart analysis. I've used it in the past and like it a lot, and if the team is open, would be happy to lead a migration.

**Comment by craiglabenz** [comment]
Inspired by #139.

**Comment by kevmoo** [comment]
I think we're good here!
