### ISSUE TITLE
Cannot regenerate server file like described in the docs

### ISSUE THREAD

**Issue by jmewes** [GoogleCloudPlatform/functions-framework-dart#178]
# Observed result

Following the steps in the [Dart quickstart](https://github.com/GoogleCloudPlatform/functions-framework-dart/blob/main/docs/quickstarts/01-quickstart-dart.md), I am geting an error message on the attempt to re-generate the `server.dart` file.

```
$ dart run build_runner build --delete-conflicting-outputs
Could not find the implicit file to run: bin/hello.dart.
```

# Expected result

It should be possible to follow the example command in the project documentation without running into errors.

# Steps to reproduce

```
git clone git@github.com:GoogleCloudPlatform/functions-framework-dart.git
cd functions-framework-dart/examples/hello
pub get
dart run build_runner build --delete-conflicting-outputs
```

# Environment

```
$ dart --version
Dart SDK version: 2.10.5 (stable) (Tue Jan 19 13:05:37 2021 +0100) on "macos_x64"
```

**Comment by kevmoo** [comment]
@jmewes – could you try with Dart 2.12? Curious if you still see this...

**Comment by jmewes** [comment]
@kevmoo ,

I have upgraded to Dart 2.12 on Ubuntu and there the requests are working as described in the README.

I assume that for Mac it will also work, but I won't test this right now because of projects which are not migrated to null safety, yet.

**Comment by subfuzion** [comment]
@jmewes Apologies for delayed response here. We just updated the Dart Functions Framework, along with all the examples, and Dart ^2.12.0 is now required ([Changelog](https://github.com/GoogleCloudPlatform/functions-framework-dart/blob/main/functions_framework/CHANGELOG.md)).

**Comment by jmewes** [comment]
@subfuzion ,

Thanks for the feedback!

**Comment by fatherOfLegends** [comment]
I am trying to generate the server file and I keep getting no output. 

Dart SDK version: 2.13.3 (stable) (Wed Jun 9 12:44:44 2021 +0200) on "macos_x64"
[INFO] Generating build script completed, took 715ms
[INFO] Reading cached asset graph completed, took 79ms
[INFO] Checking for updates since last build completed, took 656ms
[INFO] Running build completed, took 24ms
[INFO] Caching finalized dependency graph completed, took 52ms
[INFO] Succeeded after 95ms with 0 outputs (0 actions)

I feel like I must be missing something obvious.

**Comment by kevmoo** [comment]
So you have no file at `bin/server.dart`?

What does your 'lib/functions.dart` file look like?

**Comment by fatherOfLegends** [comment]
Correct, no `bin/server.dart` is generated. 
`lib/functions.dart` <- I renamed this file in my project. I thought the annotation would be enough to generate the code. Is this filename a requirement?

**Comment by kevmoo** [comment]
It is!

https://github.com/GoogleCloudPlatform/functions-framework-dart/blob/5c6990befd824806ffe03517f2fd9108313e2487/functions_framework_builder/build.yaml#L6-L8

**Comment by fatherOfLegends** [comment]
Thanks! I really appreciate you all working to make server side dart better.
