### ISSUE TITLE
Update examples/raw_cloudevent to use official image

### ISSUE THREAD

**Issue by subfuzion** [GoogleCloudPlatform/functions-framework-dart#229]
Will need to take a look at builder framework internals for `'Iterable<Object?>', which does not match the return type, 'Iterable<Object>', of the overridden method, 'StructuredSerializer.serialize'`

**Comment by kevmoo** [comment]
How do I reproduce this?

**Comment by subfuzion** [comment]
Update the Dockerfile like the other examples to use the official image, try and build.

**Comment by subfuzion** [comment]
I just looked at it again, looks like the current example probably hasn't been working for a while:

```
dart run build_runner build --delete-conflicting-outputs
```

Output:
```
$ dart run build_runner build --delete-conflicting-outputs
Precompiling executable... (5.4s)
Failed to precompile build_runner:build_runner:
...
```

**Comment by subfuzion** [comment]
This is the commit that breaks the example: [79e4e4fd](https://github.com/GoogleCloudPlatform/functions-framework-dart/commit/79e4e4fd82d2241bc03f80aa3dd7624de019b917) (PR #219).

**Comment by kevmoo** [comment]
Have you run `pub upgrade` in the directory first? It's working fine for
me...

**Comment by subfuzion** [comment]
I have. And the image doesn't build either, so that shouldn't be my environment. Anyway, why don't you just update the sample (as I originally asked) and if it works for you, then that's great. I updated the other samples.

**Comment by subfuzion** [comment]
So `git clean fdx` fixed the issue for me:

```
$ git clean -fdx
Removing .dart_tool/
Removing .packages
Removing pubspec.lock
```

But since the `.dockerignore` ensures that the first two weren't included in the docker build context, it seems that removing `pubspec.lock` is what needed to be done to fix.

So this makes me realize that we're versioning an application, but we're not committing the lock file. Not sure why not since I don't see it in `.dockerignore`.

I'm going to try adding the lock file with an update for the example. Otherwise, the fix is to run `dart pub upgrade` to force Dart to update it.

**Comment by subfuzion** [comment]
Reopening. Will close this with #230.
