### ISSUE TITLE
Logging recommendation?

### ISSUE THREAD

**Issue by jimmyff** [GoogleCloudPlatform/functions-framework-dart#248]
What is the recommended way to log debug etc? `srdout` or some sort of shelf middleware? 

 [In this example](https://github.com/GoogleCloudPlatform/functions-framework-dart/blob/main/examples/fullstack/backend/lib/functions.dart#L29) if you specify a return type then you get a second param `RequestContext` which providers access to `.logger(...)`

But if you're just using the basic shelf request, then you don't get a `RequestContext`. Although this [code here](https://github.com/GoogleCloudPlatform/functions-framework-dart/blob/main/test/hello/lib/functions.dart#L117) looks like there is some sort of support for logging from a client but I'm not sure where that `logger` is getting assigned.

Thanks

**Comment by kevmoo** [comment]
You can make your function signature look like this

https://github.com/GoogleCloudPlatform/functions-framework-dart/blob/2d9ebe336d6f006b795033b4ceaaa6d600638522/integration_test/lib/functions.dart#L115

And you'll get access to the logger!
