### ISSUE TITLE
Docker build failing

### ISSUE THREAD

**Issue by DavoSwain** [GoogleCloudPlatform/functions-framework-dart#268]
Having an issue with the docker build on the hello world example, getting the following feedback:

#9 5.446 Downloading vm_service 7.2.0...
#9 125.7 Connection closed before full header was received
------
executor failed running [/bin/sh -c dart pub get]: exit code: 69

Any suggestions on a fix?

**Comment by Mooibroek** [comment]
Also running into a docker build failure. 
Steps to reproduce:

- Creating a helloworld application, 
- Running `dart run bin/server.dart` works fine locally
- Running `docker build .`  and after that `docker run [container_name]` 

This error pops up:

`standard_init_linux.go:228: exec user process caused: no such file or directory`

Any thoughts?

**Comment by kevmoo** [comment]
I just did

```
docker build -t dart-server .
run -it --rm -p 8080:8080 --name myserver dart-server
```

no problem.

If you try to run `/bin/sh` or similar that will fail because that command does not exist in the compiled image. It's from `scratch` which is tiny

**Comment by weenzeel** [comment]
I'm also getting the "standard_init_linux.go:228: exec user process caused: no such file or directory" error message as reported by @Mooibroek above.

Steps to reproduce.

Run `dartfn generate helloworld` in a new folder.

As instructed by the README file. Run commands ...

```
docker build -t hello .
docker run -it -p 8080:8080 --name app hello
```

**Comment by weenzeel** [comment]
@Mooibroek If you created your project via the dartfn tool it may be that you've got a faulty docker file. Try and add a line similar to ...

`COPY --from=0 /runtime/ /`

to get the runtime needed by the server in the final runt-time Docker image.

**Comment by kevmoo** [comment]
We clearly need to fix something here...will take a look!

**Comment by kevmoo** [comment]
This is now fixed – thanks to @subfuzion – update `dartfn` and you should be good to go!
