### ISSUE TITLE
Dockerfile can be a lot more simple

### ISSUE THREAD

**Issue by kevmoo** [GoogleCloudPlatform/functions-framework-dart#27]
https://github.com/GoogleCloudPlatform/functions-framework-dart/blob/3b4d7ca01ad4a3c09884aef46c0539f69b6f505f/Dockerfile#L5-L15

We don't need `mono_repo`. We can just run `pub get` on the example app directory. Everything else is not needed.

**Comment by subfuzion** [comment]
Sounds good!

**Comment by subfuzion** [comment]
Thanks, good call on removing mono_repo. Still need to copy the pubspecs for it to build and cache all the deps, but after that, unless pubspecs get updated, only need to build new image layers based on modified sources and cached deps.
