### ISSUE TITLE
sample project created via dartfn should use official docker images

### ISSUE THREAD

**Issue by weenzeel** [GoogleCloudPlatform/functions-framework-dart#277]
Hi!

When scaffolding a new project via the dartfn cli tool, the generated docker image is not the official one from DockerHub. The official image is included in the example folders of this project looks like the official one, but the file in the template folders used by the dartfn tool seems to be an older version.

Could this be corrected so that we always get the official image for new projects?

Thanks!

**Comment by weenzeel** [comment]
Great job! Thanks! 👍

**Comment by kevmoo** [comment]
This is now fixed – thanks to @subfuzion – update `dartfn` and you should be good to go!

**Comment by kevmoo** [comment]
er, sorry – wrong bug!
