### ISSUE TITLE
Generated project (from dartfn) logs CloudEvent awkwardly

### ISSUE THREAD

**Issue by craiglabenz** [GoogleCloudPlatform/functions-framework-dart#351]
The generated file from `dartfn` [contains this code in `lib/functions.dart`](https://github.com/GoogleCloudPlatform/functions-framework-dart/blob/3a637639d44a09da554aa6eef70b3e3b112df0dc/dartfn/templates/cloudevent/lib/functions.dart#L12)

```dart
stderr.writeln(_encoder.convert(event));
```

Which renders awkwardly in the Cloud Run console with extraneous newlines and separate log statements.

<img width="900" alt="Screen Shot 2022-10-31 at 12 59 24 PM" src="https://user-images.githubusercontent.com/855034/199100293-f63df72a-aeca-4d4b-84f9-869bb2c1d5e2.png">

**Comment by kevmoo** [comment]
Weird indeed!

**Comment by craiglabenz** [comment]
I could play with this, but I'll pretty much just be trying random things and re-deploying until something changes with no real theory of which layer is overly splitting the message.

If you have any ideas of where to start, I can tinker.

**Comment by kevmoo** [comment]
I think I get it. It's just multi-line text by the time it gets to the logger.

It's *possible* that if we just emit it as valid JSON in a single line, it'd format better on Cloud – but we harder to understand on the local console.

Not sure this is a bug in THIS project, or just a quirk of how Cloud logging works.

What would you like changed?

(The newlines are not extraneous, it's just how Cloud Logging handles multi-line prints)
