### ISSUE TITLE
BuildRunner seems to break the code

### ISSUE THREAD

**Issue by mark-dropbear** [GoogleCloudPlatform/functions-framework-dart#426]
This is the diff of running the build runner along with the error message in the terminal. I should note this is a blank template from the hello world example.
![image](https://github.com/GoogleCloudPlatform/functions-framework-dart/assets/76698672/690085ba-85d2-487e-bec1-5879ce8b0b28)

**Comment by kevmoo** [comment]
Are you running Dart 3 or later?

**Comment by mark-dropbear** [comment]
```bash
dart --version
Dart SDK version: 3.0.7 (stable) (None) on "linux_x64"
```

**Comment by kevmoo** [comment]
Oh! Do you have your SDK constraint set to `^3.0.0`? That enables the new features!

**Comment by mark-dropbear** [comment]
Well spotted. But worth pointing out that is the default output of running `dartfn` at the moment.
![Screenshot 2023-08-12 00 28 15](https://github.com/GoogleCloudPlatform/functions-framework-dart/assets/76698672/0a2ee2da-20e5-40d8-9ed0-4d1da8a21afe)

**Comment by kevmoo** [comment]
Great catch ! I need to deploy a new `dartfn`!

**Comment by mark-dropbear** [comment]
I really love the package by the way. Hope it continues to find more users but I actually consider it one of the better starting places on the internet for a new project. Simple interface, deeply integrated to GCP / Firebase, nothing to manage. It's nice, thank you again.

**Comment by kevmoo** [comment]
See https://github.com/GoogleCloudPlatform/functions-framework-dart/pull/430
